language: python
python:
  - "2.7.6"
# command to install dependencies
#sudo: required
install: 
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
# command to run tests
script: bash run_tests.sh -N -P
